# Generated by Django 5.1.1 on 2024-10-20 22:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hotel_room_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.hotel_image_path),
        ),
    ]
